import { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Navbar from "./Navbar";
import PropTypes from "prop-types";
import NProgress from "nprogress";
import nProgress from "nprogress";
import classNames from "classnames";

const Layout = ({ children, title, footer = true, dark = false }) => {
  const router = useRouter();

  useEffect(() => {
    const handleRouteChange = (url) => {
      console.log(url);
      NProgress.start();
    };

    router.events.on("routeChangeStart", handleRouteChange);

    router.events.on("routeChangeComplete", () => NProgress.done());

    router.events.on("routeChangeError", () => nProgress.done());

    return () => {
      router.events.off("routeChangeStart", handleRouteChange);
    };
  }, []);

  return (
    <div className={classNames({ "bg-dark": dark, "bg-light": !dark })}>
      <Head>
        <title>MAGREY PREMIUM {title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Navbar />
      <main className="container py-4">
        {/* Title */}
        {title && (
          <h1 className={classNames("text-center", { "text-light": dark })}>
            {title}
          </h1>
        )}

        {/* Content */}
        {children}
      </main>

      {footer && (
        <footer className="bg-dark text-light text-center">
          <div className="container p-4">
            <h1>&copy; MAGREY PREMIUM BARBER</h1>
            <a
              href="https://api.whatsapp.com/send/?phone=573217100215&text&type=phone_number&app_absent=0"
              target="_blank"
              rel="noopener"
            >
              <img src="/whatsapp.svg" alt="" />
            </a>
            <a href="https://www.instagram.com" target="_blank" rel="noopener">
              <img src="/instagram.svg" alt="" />
            </a>
            <a href="https://www.tiktok.com" target="_blank" rel="noopener">
              <img src="/tiktok.svg" alt="" />
            </a>
            <a
              href="https://www.google.com/maps/@6.2625416,-75.5889357,3a,75y,115.58h,90t/data=!3m7!1e1!3m5!1sp0fUnBK8FZ7V-ZjdHjKBVg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3Dp0fUnBK8FZ7V-ZjdHjKBVg%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D115.71792%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192"
              target="_blank"
              rel="noopener"
            >
              <img src="/maps.svg" alt="" />
            </a>
            <a href="https://www.facebook.com" target="_blank" rel="noopener">
              <img src="/facebook.svg" alt="" />
            </a>
            <p>2014 - {new Date().getFullYear()}</p>
          </div>
        </footer>
      )}
    </div>
  );
};

Layout.proptypes = {
  children: PropTypes.node,
  title: PropTypes.string,
  footer: PropTypes.bool,
};

export default Layout;
